---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name: [
      'git',
      'build-essential',
      'cpanminus',
      'libssl-dev',
      'libpq-dev',
      'libz-dev',
      'libexpat1-dev',
      'vim',
      'postgresql-client',
      'postgresql-contrib',
      'postgresql',
      'python3-psycopg2',
      'nginx',
      'certbot',
      'curl',
      'python3-certbot-nginx',
    ]
    state: present

- name: start postgresql
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create db user account for weightgrapher
  postgresql_user:
    name: "{{ database.weightgrapher.user }}"
    password: "{{ database.weightgrapher.pass }}"
    state: present
  become_user: postgres
  become: true

- name: Create weightgrapher database
  postgresql_db:
    name: "{{ database.weightgrapher.name }}"
    owner: "{{ database.weightgrapher.user }}"
    state: present
  become_user: postgres
  become: true

- name: Create manager user
  user:
    name: manager
    shell: /bin/bash
    comment: WeightGrapher Manager User Account

- name: Create ~manager/.ssh
  file:
    state: directory
    path: /home/manager/.ssh
    owner: manager
    group: manager
    mode: 0700

- name: Create ~manager/.ssh/authorized_keys from ~root
  copy:
    dest: /home/manager/.ssh/authorized_keys
    src: /root/.ssh/authorized_keys
    remote_src: true
    owner: manager
    group: manager
    mode: 0600

- name: Install /etc/weightgrapher.yml
  template:
    src: "{{ role_path }}/templates/weightgrapher.yml.j2"
    dest: /etc/weightgrapher.yml
    owner: root
    group: root
    mode: 0644

- name: Install ~/.vimrc for root.
  copy:
    dest: /root/.vimrc
    src: "{{ role_path }}/files/vimrc"
    owner: root
    group: root
    mode: 0644

- name: Install ~/.vimrc for manager.
  copy:
    dest: /home/manager/.vimrc
    src: "{{ role_path }}/files/vimrc"
    owner: manager
    group: manager
    mode: 0644

- name: "Git clone from https://github.com/yko/mojo.vim.git"
  git:
    repo: "https://github.com/yko/mojo.vim.git"
    dest: /home/manager/mojo.vim
    accept_hostkey: true
  become: true
  become_user: manager

- name: Install mojo.vim plugin
  shell: make install
  args:
    chdir: /home/manager/mojo.vim
  become: true
  become_user: manager

- name: "Git clone from {{ repo }}"
  git:
    repo: "{{ repo }}"
    dest: /home/manager/weightgrapher
    accept_hostkey: true
  become: true
  become_user: manager

- name: Install Dist::Zilla
  shell: cpanm Dist::Zilla
  environment:
    PATH:                '/home/manager/perl5/bin:/usr/local/bin:/usr/bin:/bin'
    PERL5LIB:            '/home/manager/perl5/lib/perl5'
    PERL_MB_OPT:         '--install_base "/home/manager/perl5"'
    PERL_MM_OPT:         'INSTALL_BASE=/home/manager/perl5'
    PERL_LOCAL_LIB_ROOT: '/home/manager/perl5'
  become: true
  become_user: manager

- name: Build WeightGrapher::DB
  shell: dzil build
  args:
    chdir: /home/manager/weightgrapher/DB
  environment:
    PATH:                '/home/manager/perl5/bin:/usr/local/bin:/usr/bin:/bin'
    PERL5LIB:            '/home/manager/perl5/lib/perl5'
    PERL_MB_OPT:         '--install_base "/home/manager/perl5"'
    PERL_MM_OPT:         'INSTALL_BASE=/home/manager/perl5'
    PERL_LOCAL_LIB_ROOT: '/home/manager/perl5'
  become: true
  become_user: manager

- name: Install WeightGrapher::DB
  shell: cpanm WeightGrapher-DB-*.tar.gz
  args:
    chdir: /home/manager/weightgrapher/DB
  environment:
    PATH:                '/home/manager/perl5/bin:/usr/local/bin:/usr/bin:/bin'
    PERL5LIB:            '/home/manager/perl5/lib/perl5'
    PERL_MB_OPT:         '--install_base "/home/manager/perl5"'
    PERL_MM_OPT:         'INSTALL_BASE=/home/manager/perl5'
    PERL_LOCAL_LIB_ROOT: '/home/manager/perl5'
  become: true
  become_user: manager

- name: Install WeightGrapher::Web Dependencies
  shell: cpanm --installdeps .
  args:
    chdir: /home/manager/weightgrapher/Web
  environment:
    PATH:                '/home/manager/perl5/bin:/usr/local/bin:/usr/bin:/bin'
    PERL5LIB:            '/home/manager/perl5/lib/perl5'
    PERL_MB_OPT:         '--install_base "/home/manager/perl5"'
    PERL_MM_OPT:         'INSTALL_BASE=/home/manager/perl5'
    PERL_LOCAL_LIB_ROOT: '/home/manager/perl5'

  become: true
  become_user: manager

- name: Import the WeightGrapher database
  shell: /home/manager/weightgrapher/Web/script/weightgrapher dbc < /home/manager/weightgrapher/DB/etc/schema.sql > /home/manager/weightgrapher/DB/etc/schema.log
  environment:
    PATH:                '/home/manager/perl5/bin:/usr/local/bin:/usr/bin:/bin'
    PERL5LIB:            '/home/manager/perl5/lib/perl5'
    PERL_MB_OPT:         '--install_base "/home/manager/perl5"'
    PERL_MM_OPT:         'INSTALL_BASE=/home/manager/perl5'
    PERL_LOCAL_LIB_ROOT: '/home/manager/perl5'
  become: true
  become_user: manager

- name: Install weightgrapher.service file.
  copy:
    dest: /etc/systemd/system/weightgrapher.service
    src: "{{ role_path }}/files/weightgrapher.service"
    owner: root
    group: root
    mode: 0644

- name: Start WeightGrapher
  service:
    name: weightgrapher
    state: restarted
    enabled: true

- name: "Install /etc/nginx/sites-enabled/{{ domain_name }}"
  template:
    src: "{{ role_path }}/templates/nginx-domain.j2"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
    owner: root
    group: root
    mode: 0644

- name: start nginx
  service:
    name: nginx
    state: restarted
